#+STARTUP: showeverything

-- do the reduction, coef0? -> in the dump
   It has to be the slope or ACPeval will not work.

* High-level operations

INSERT OLDDAT [directory.s] [NOREFERENCE]

  Insert data in bulk from old-style ACP data files. Requires the
  definition of a complete training set.

  The data files all reside in the indicated directory (in ./ if not
  given). This command first searches for the file called names.dat,
  and verifies that the names in it match with those in the current
  training set. This is done to ensure the integrity of the
  database. After this operation is complete, the following data is
  read and inserted:

  - ref.dat: evaluation of the reference method in the training
    set. The reference is not inserted if NOREFERENCE is present.

  - empty.dat: evaluation of the empty method in the training set.

  - x_y_z.dat, where x is the atom (lowercase symbol), y is the
    angular momentum (lowercase), and z is the exponent index. Insert
    the corresponding ACP term.

  In all cases, the insertion verifies that the file contains exactly
  the same number of entries as the current training set. Due to the
  nature of this operation, avoid having NOFIT subsets in the training
  set when using INSERT OLDDAT.

  trainset -> insert_olddat

DUMP

  Write the octavedump.dat file for the LASSO fit corresponding to the
  current dataset.

  trainset -> dump

-- automatic testing on github & upload zz_source
-- clean up extra keywords and code in trainset and acpdb --
-- copy over from the code --
-- build energy differences from total energies --
-- own implementation of LASSO in c++ --
-- how to maxcoef, nonlinearity, critic2 to run ECPs with the libecp
-- build all the databases

