#+STARTUP: showeverything

* Command-line syntax

apcfit -h [inputfile [outputfile]]

The input file is a keyword-driven case-insensitive text
file. Comments are #. If the input or the output file are not present,
stdin and stdout are used. If the output file is not present, stdout
is used.

* Definitions

- Structure: the structural information about a molecule or crystal.

- Property: a quantity calculable by running a few molecular or
  crystal calculations and that is linear in the total energies. 

- Method: a method for the calculation of a property. Can be a
  "reference method" (expensive and/or from the literature), an
  approximate method (usually the target of ACP fitting), or an
  additional method (additional contributions to the energy, like a
  dispersion correction).

- Set: a group of properties, usually from an article in the
  literature and calculated with a reasonably good method.

- Traning set: the set of all properties that are used for ACP
  development. Comprises one or more sets.

- Dataset: the training set plus additional information such as atoms,
  angular momentum channels, etc. The dataset completely determines
  the ACP fitting problem.

Whenver set names are required, an asterisk stands for the current
training set. When a method name is required, an asterisk stands for
the method used in the original reference.

* Keywords

CREATE acpdb_file.s

  Creates an empty database in file acpdb_file.s.

CONNECT acpdb_file.s

  Connects to the database file acpdb_file.s.

DISCONNECT

  Disconnect the current database.

INSERT LITREF ref.s
  AUTHORS ... 
  TITLE ...
  JOURNAL ... 
  VOLUME ...
  PAGE ...
  YEAR ...
  DOI ... 
  DESCRIPTION ... 
END

  Insert a new literature reference into the database (table 1), with
  key ref.s. The key and the DOI must be unique.

INSERT LITREF BIBTEX bibfile.s

  Insert the literature references contained in bibtex file
  bibfile.s. Only entries of type article are inserted.

DELETE LITREF {key.s|key.i|*}

  Delete a literature reference using the reference key or id
  number. If *, delete all literature references.

LIST LITREF [BIBTEX]

  List the literature references in the database. If the BIBTEX
  keyword is used, write the list of literature referneces in bibtex
  format.

INSERT SET name.s
  PROPERTY_TYPE {prop.s|prop.i}
  DESCRIPTION ...
  NSTRUCTURES nstruct.i
  NPROPERTIES nprop.i
  LITREFS {ref1.s|ref1.i} {ref2.s|ref2.i} ...
END

  Insert a set with name name.s in the database. The set calculates
  property prop.s/prop.i from Property_types and has nstruct.i
  structures. One or more references from Table 1 can be given by id
  or key.

DELETE SET {set.s|set.i}

  Delete a set (Table 3).

LIST SET

  List the known sets.

INSERT METHOD name.s
  COMP_DETAILS ...
  LITREFS {ref1.s|ref1.i} {ref2.s|ref2.i} ...
  DESCRIPTION ...
END    

  Insert a computational method with name name.s in the database. The
  method has computational details COMP_DETAILS. LITREFS: literature
  references. DESCRIPTION: a description of the method.

* Database schema

** Table 1: literature references (Literature_refs)

- id          INTEGER PRIMARY KEY NOT NULL
- key         TEXT UNIQUE NOT NULL
- authors     TEXT
- title       TEXT
- journal     TEXT
- volume      TEXT
- page        TEXT
- year        TEXT
- doi         TEXT UNIQUE
- description TEXT

** Table 2: property types (Property_types)

- id          INTEGER PRIMARY KEY NOT NULL
- key         TEXT UNIQUE NOT NULL
- description TEXT

** Table 3: sets

- id            INTEGER PRIMARY KEY NOT NULL,
- key           TEST UNIQUE NOT NULL,
- property_type INTEGER NOT NULL,   
- nstructures   INTEGER NOT NULL,
- nproperties   INTEGER NOT NULL,
- description   TEXT
- litrefs       TEXT,

** Table 4: methods

- id            INTEGER PRIMARY KEY NOT NULL,
- key           TEXT UNIQUE NOT NULL,
- comp_details  TEXT,
- litrefs       TEXT,
- description   TEXT,

